lat := 40.6972
lng := -74.1143
india_lat := 13.0475255
india_lng := 80.2086733
hongkong_lat := 22.3529584
hongkong_lng := 113.974593

.PHONY: run india
run:
	bash -c ".local/night-and-day/runner.sh $(lat) $(lng)"

china:
	bash -c ".local/night-and-day/runner.sh $(hongkong_lat) $(hongkong_lng)"



